using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;

namespace Statistics.World;

public class Country
{
	public int Id { get; set; }
	public string Name { get; set; }

	public string Code { get; set; }

	public virtual ICollection<Population> Populations { get; set; }

	/// <summary>
	/// Pull countries from the dictionary and store them in the database
	/// </summary>
	/// <returns>Returns true if successfull, false if unsuccessfull</returns>
	public static async Task<bool> Update()
	{
		using Context context = new();

		bool returner = false;

		try
		{
			// Throws ArgumentNull
			context.Countries.Load();

			IEnumerable<Country> countries1 =
				IsoCodes.Select(
					x => new Country
					{
						Name = x.Key,
						Code = x.Value
					});

			IEnumerable<Country> countries2 =
				WorldBankCodes.Select(
					x => new Country
					{
						Name = x.Key,
						Code = x.Value
					});

			// DistinctBy Country.Code
			IEnumerable<Country> countries = countries1
				.Concat(countries2)
				.GroupBy(c => c.Code)
				.Select(g => g.First());

			// Filter out countries that already exist in the database
			countries = countries.Where(x => !context.Countries.Any(y => y.Code == x.Code));

			context.Countries.AddRange(countries);

			// Throws dbupdate exception
			int changes = await context.SaveChangesAsync();

			// Report to user
			string text = $"{changes} countries saved to database.";
			string caption = "Database Updated";
			MessageBox.Show(text, caption, MessageBoxButton.OK);

			returner = true;
		}

		catch (ArgumentNullException ex)
		{
			string text = $"Source was null when loading countries from database. Countries will not be loaded.\n\n{ex.Message}";
			string caption = "Database Error";
			MessageBox.Show(text, caption, MessageBoxButton.OK);
		}

		catch (DbUpdateException ex)
		{
			string text = $"There was a problem saving the database.\n\n{ex.Message}";
			string caption = "Database Error";
			MessageBox.Show(text, caption, MessageBoxButton.OK);
		}

		catch (Microsoft.Data.Sqlite.SqliteException ex)
		{
			string text = $"There was a problem with the database while loading countries.\n\n{ex.Message}";
			string caption = "Database Error";
			MessageBox.Show(text, caption, MessageBoxButton.OK);
		}

		return returner;
	}

	public static Dictionary<string, string> IsoCodes { get; } = new()
	{
		{ "Afghanistan", "AFG" },
		{ "Albania", "ALB" },
		{ "Algeria", "DZA" },
		{ "American Samoa", "ASM" },
		{ "Andorra", "AND" },
		{ "Angola", "AGO" },
		{ "Antigua And Barbuda", "ATG" },
		{ "Argentina", "ARG" },
		{ "Armenia", "ARM" },
		{ "Aruba", "ABW" },
		{ "Australia", "AUS" },
		{ "Austria", "AUT" },
		{ "Azerbaijan", "AZE" },
		{ "Bahamas", "BHS" },
		{ "Bahrain", "BHR" },
		{ "Bangladesh", "BGD" },
		{ "Barbados", "BRB" },
		{ "Belarus", "BLR" },
		{ "Belgium", "BEL" },
		{ "Belize", "BLZ" },
		{ "Benin", "BEN" },
		{ "Bermuda", "BMU" },
		{ "Bhutan", "BTN" },
		{ "Bolivia", "BOL" },
		{ "Bosnia And Herzegovina", "BIH" },
		{ "Botswana", "BWA" },
		{ "Brazil", "BRA" },
		{ "Brunei", "BRN" },
		{ "Bulgaria", "BGR" },
		{ "Burkina Faso", "BFA" },
		{ "Burundi", "BDI" },
		{ "Cambodia", "KHM" },
		{ "Cameroon", "CMR" },
		{ "Canada", "CAN" },
		{ "Cape Verde", "CPV" },
		{ "Cayman Islands", "CYM" },
		{ "Central African Republic", "CAF" },
		{ "Chad", "TCD" },
		{ "Chile", "CHL" },
		{ "China", "CHN" },
		{ "Colombia", "COL" },
		{ "Comoros", "COM" },
		{ "Congo", "COD" },
		{ "Costa Rica", "CRI" },
		{ "Croatia", "HRV" },
		{ "Cuba", "CUB" },
		{ "Cyprus", "CYP" },
		{ "Czech Republic", "CZE" },
		{ "Denmark", "DNK" },
		{ "Djibouti", "DJI" },
		{ "Dominica", "DMA" },
		{ "Dominican Republic", "DOM" },
		{ "East Timor", "TLS" },
		{ "Ecuador", "ECU" },
		{ "Egypt", "EGY" },
		{ "El Salvador", "SLV" },
		{ "Equatorial Guinea", "GNQ" },
		{ "Eritrea", "ERI" },
		{ "Estonia", "EST" },
		{ "Ethiopia", "ETH" },
		{ "Euro Area", "EUR" },
		{ "European Union", "EU" },
		{ "Fiji", "FJI" },
		{ "Finland", "FIN" },
		{ "France", "FRA" },
		{ "Gabon", "GAB" },
		{ "Gambia", "GMB" },
		{ "Georgia", "GEO" },
		{ "Germany", "DEU" },
		{ "Ghana", "GHA" },
		{ "Greece", "GRC" },
		{ "Greenland", "GRL" },
		{ "Grenada", "GRD" },
		{ "Guam", "GUM" },
		{ "Guatemala", "GTM" },
		{ "Guinea", "GIN" },
		{ "Guinea Bissau", "GNB" },
		{ "Guyana", "GUY" },
		{ "Haiti", "HTI" },
		{ "Honduras", "HND" },
		{ "Hong Kong", "HKG" },
		{ "Hungary", "HUN" },
		{ "Iceland", "ISL" },
		{ "India", "IND" },
		{ "Indonesia", "IDN" },
		{ "Iran", "IRN" },
		{ "Iraq", "IRQ" },
		{ "Ireland", "IRL" },
		{ "Isle Of Man", "IMN" },
		{ "Israel", "ISR" },
		{ "Italy", "ITA" },
		{ "Ivory Coast", "CIV" },
		{ "Jamaica", "JAM" },
		{ "Japan", "JPN" },
		{ "Jordan", "JOR" },
		{ "Kazakhstan", "KAZ" },
		{ "Kenya", "KEN" },
		{ "Kiribati", "KIR" },
		{ "Kosovo", "XKX" },
		{ "Kuwait", "KWT" },
		{ "Kyrgyzstan", "KGZ" },
		{ "Laos", "LAO" },
		{ "Latvia", "LVA" },
		{ "Lebanon", "LBN" },
		{ "Lesotho", "LSO" },
		{ "Liberia", "LBR" },
		{ "Libya", "LBY" },
		{ "Liechtenstein", "LIE" },
		{ "Lithuania", "LTU" },
		{ "Luxembourg", "LUX" },
		{ "Macau", "MAC" },
		{ "Macedonia", "MKD" },
		{ "Madagascar", "MDG" },
		{ "Malawi", "MWI" },
		{ "Malaysia", "MYS" },
		{ "Maldives", "MDV" },
		{ "Mali", "MLI" },
		{ "Malta", "MLT" },
		{ "Marshall Islands", "MHL" },
		{ "Mauritania", "MRT" },
		{ "Mauritius", "MUS" },
		{ "Mexico", "MEX" },
		{ "Micronesia", "FSM" },
		{ "Moldova", "MDA" },
		{ "Monaco", "MCO" },
		{ "Mongolia", "MNG" },
		{ "Montenegro", "MNE" },
		{ "Morocco", "MAR" },
		{ "Mozambique", "MOZ" },
		{ "Myanmar", "MMR" },
		{ "Namibia", "NAM" },
		{ "Nepal", "NPL" },
		{ "Netherlands", "NLD" },
		{ "New Caledonia", "NCL" },
		{ "New Zealand", "NZL" },
		{ "Nicaragua", "NIC" },
		{ "Niger", "NER" },
		{ "Nigeria", "NGA" },
		{ "North Korea", "PRK" },
		{ "Norway", "NOR" },
		{ "Oman", "OMN" },
		{ "Pakistan", "PAK" },
		{ "Palau", "PLW" },
		{ "Palestine", "PSE" },
		{ "Panama", "PAN" },
		{ "Papua New Guinea", "PNG" },
		{ "Paraguay", "PRY" },
		{ "Peru", "PER" },
		{ "Philippines", "PHL" },
		{ "Poland", "POL" },
		{ "Portugal", "PRT" },
		{ "Puerto Rico", "PRI" },
		{ "Qatar", "QAT" },
		{ "Republic Of The Congo", "COG" },
		{ "Romania", "ROU" },
		{ "Russia", "RUS" },
		{ "Rwanda", "RWA" },
		{ "Samoa", "WSM" },
		{ "Sao Tome And Principe", "STP" },
		{ "Saudi Arabia", "SAU" },
		{ "Senegal", "SEN" },
		{ "Serbia", "SRB" },
		{ "Seychelles", "SYC" },
		{ "Sierra Leone", "SLE" },
		{ "Singapore", "SGP" },
		{ "Slovakia", "SVK" },
		{ "Slovenia", "SVN" },
		{ "Solomon Islands", "SLB" },
		{ "Somalia", "SOM" },
		{ "South Africa", "ZAF" },
		{ "South Korea", "KOR" },
		{ "South Sudan", "SSD" },
		{ "Spain", "ESP" },
		{ "Sri Lanka", "LKA" },
		{ "St Kitts And Nevis", "KNA" },
		{ "St Lucia", "LCA" },
		{ "St Vincent And The Grenadines", "VCT" },
		{ "Sudan", "SDN" },
		{ "Suriname", "SUR" },
		{ "Swaziland", "SWZ" },
		{ "Sweden", "SWE" },
		{ "Switzerland", "CHE" },
		{ "Syria", "SYR" },
		{ "Taiwan", "TWN" },
		{ "Tajikistan", "TJK" },
		{ "Tanzania", "TZA" },
		{ "Thailand", "THA" },
		{ "Togo", "TGO" },
		{ "Tonga", "TON" },
		{ "Trinidad And Tobago", "TTO" },
		{ "Tunisia", "TUN" },
		{ "Turkey", "TUR" },
		{ "Turkmenistan", "TKM" },
		{ "Uganda", "UGA" },
		{ "Ukraine", "UKR" },
		{ "United Arab Emirates", "ARE" },
		{ "United Kingdom", "GBR" },
		{ "United States", "USA" },
		{ "Uruguay", "URY" },
		{ "Uzbekistan", "UZB" },
		{ "Vanuatu", "VUT" },
		{ "Venezuela", "VEN" },
		{ "Vietnam", "VNM" },
		{ "Yemen", "YEM" },
		{ "Zambia", "ZMB" },
		{ "Zimbabwe", "ZWE" },
	};

	public static Dictionary<string, string> WorldBankCodes { get; } = new()
	{
		{ "Afghanistan", "AFG" },
		{ "Africa", "AFR" },
		{ "Albania", "ALB" },
		{ "Algeria", "DZA" },
		{ "American Samoa", "ASM" },
		{ "Andorra", "AND" },
		{ "Angola", "AGO" },
		{ "Antigua And Barbuda", "ATG" },
		{ "Arab World", "ARB" },
		{ "Argentina", "ARG" },
		{ "Armenia", "ARM" },
		{ "Aruba", "ABW" },
		{ "Australia", "AUS" },
		{ "Austria", "AUT" },
		{ "Azerbaijan", "AZE" },
		{ "Bahamas, The", "BHS" },
		{ "Bahrain", "BHR" },
		{ "Bangladesh", "BGD" },
		{ "Barbados", "BRB" },
		{ "Belarus", "BLR" },
		{ "Belgium", "BEL" },
		{ "Belize", "BLZ" },
		{ "Benin", "BEN" },
		{ "Bermuda", "BMU" },
		{ "Bhutan", "BTN" },
		{ "Bolivia", "BOL" },
		{ "Bosnia And Herzegovina", "BIH" },
		{ "Botswana", "BWA" },
		{ "Brazil", "BRA" },
		{ "Brunei Darussalam", "BRN" },
		{ "Bulgaria", "BGR" },
		{ "Burkina Faso", "BFA" },
		{ "Burundi", "BDI" },
		{ "Cabo Verde", "CPV" },
		{ "Cambodia", "KHM" },
		{ "Cameroon", "CMR" },
		{ "Canada", "CAN" },
		{ "Caribbean Small States", "CSS" },
		{ "Cayman Islands", "CYM" },
		{ "Central African Republic", "CAF" },
		{ "Chad", "TCD" },
		{ "Channel Islands", "CHI" },
		{ "Chile", "CHL" },
		{ "China", "CHN" },
		{ "Colombia", "COL" },
		{ "Comoros", "COM" },
		{ "Congo, Dem. Rep.", "COD" },
		{ "Congo, Rep.", "COG" },
		{ "Costa Rica", "CRI" },
		{ "Cote D'Ivoire", "CIV" },
		{ "Croatia", "HRV" },
		{ "Cuba", "CUB" },
		{ "Curacao", "CUW" },
		{ "Cyprus", "CYP" },
		{ "Czech Republic", "CZE" },
		{ "Denmark", "DNK" },
		{ "Djibouti", "DJI" },
		{ "Dominican Republic", "DOM" },
		{ "Dominica", "DMA" },
		{ "East Asia & Pacific (All Income Levels)", "EAS" },
		{ "East Asia & Pacific (Developing Only)", "EAP" },
		{ "East Asia And The Pacific (Ifc Classification)", "CEA" },
		{ "Ecuador", "ECU" },
		{ "Egypt, Arab Rep.", "EGY" },
		{ "El Salvador", "SLV" },
		{ "Equatorial Guinea", "GNQ" },
		{ "Eritrea", "ERI" },
		{ "Estonia", "EST" },
		{ "Ethiopia", "ETH" },
		{ "Euro Area", "EMU" },
		{ "Europe & Central Asia (All Income Levels)", "ECS" },
		{ "Europe & Central Asia (Developing Only)", "ECA" },
		{ "Europe And Central Asia (Ifc Classification)", "CEU" },
		{ "European Union", "EUU" },
		{ "Faeroe Islands", "FRO" },
		{ "Fiji", "FJI" },
		{ "Finland", "FIN" },
		{ "France", "FRA" },
		{ "French Polynesia", "PYF" },
		{ "Gabon", "GAB" },
		{ "Gambia, The", "GMB" },
		{ "Georgia", "GEO" },
		{ "Germany", "DEU" },
		{ "Ghana", "GHA" },
		{ "Greece", "GRC" },
		{ "Greenland", "GRL" },
		{ "Grenada", "GRD" },
		{ "Guam", "GUM" },
		{ "Guatemala", "GTM" },
		{ "Guinea-Bissau", "GNB" },
		{ "Guinea", "GIN" },
		{ "Guyana", "GUY" },
		{ "Haiti", "HTI" },
		{ "Heavily Indebted Poor Countries (Hipc)", "HPC" },
		{ "High Income: Nonoecd", "NOC" },
		{ "High Income: Oecd", "OEC" },
		{ "High Income", "HIC" },
		{ "Honduras", "HND" },
		{ "Hong Kong Sar, China", "HKG" },
		{ "Hungary", "HUN" },
		{ "Iceland", "ISL" },
		{ "India", "IND" },
		{ "Indonesia", "IDN" },
		{ "Iran, Islamic Rep.", "IRN" },
		{ "Iraq", "IRQ" },
		{ "Ireland", "IRL" },
		{ "Isle Of Man", "IMN" },
		{ "Israel", "ISR" },
		{ "Italy", "ITA" },
		{ "Jamaica", "JAM" },
		{ "Japan", "JPN" },
		{ "Jordan", "JOR" },
		{ "Kazakhstan", "KAZ" },
		{ "Kenya", "KEN" },
		{ "Kiribati", "KIR" },
		{ "Korea, Dem. Rep.", "PRK" },
		{ "Korea, Rep.", "KOR" },
		{ "Kosovo", "KSV" },
		{ "Kuwait", "KWT" },
		{ "Kyrgyz Republic", "KGZ" },
		{ "Lao Pdr", "LAO" },
		{ "Latin America & Caribbean (All Income Levels)", "LCN" },
		{ "Latin America & Caribbean (Developing Only)", "LAC" },
		{ "Latin America And The Caribbean (Ifc Classification)", "CLA" },
		{ "Latvia", "LVA" },
		{ "Least Developed Countries: Un Classification", "LDC" },
		{ "Lebanon", "LBN" },
		{ "Lesotho", "LSO" },
		{ "Liberia", "LBR" },
		{ "Libya", "LBY" },
		{ "Liechtenstein", "LIE" },
		{ "Lithuania", "LTU" },
		{ "Low & Middle Income", "LMY" },
		{ "Low Income", "LIC" },
		{ "Lower Middle Income", "LMC" },
		{ "Luxembourg", "LUX" },
		{ "Macao Sar, China", "MAC" },
		{ "Macedonia, Fyr", "MKD" },
		{ "Madagascar", "MDG" },
		{ "Malawi", "MWI" },
		{ "Malaysia", "MYS" },
		{ "Maldives", "MDV" },
		{ "Mali", "MLI" },
		{ "Malta", "MLT" },
		{ "Marshall Islands", "MHL" },
		{ "Mauritania", "MRT" },
		{ "Mauritius", "MUS" },
		{ "Mexico", "MEX" },
		{ "Micronesia, Fed. Sts.", "FSM" },
		{ "Middle East & North Africa (All Income Levels)", "MEA" },
		{ "Middle East & North Africa (Developing Only)", "MNA" },
		{ "Middle East And North Africa (Ifc Classification)", "CME" },
		{ "Middle Income", "MIC" },
		{ "Moldova", "MDA" },
		{ "Monaco", "MCO" },
		{ "Mongolia", "MNG" },
		{ "Montenegro", "MNE" },
		{ "Morocco", "MAR" },
		{ "Mozambique", "MOZ" },
		{ "Myanmar", "MMR" },
		{ "Namibia", "NAM" },
		{ "Nepal", "NPL" },
		{ "Netherlands", "NLD" },
		{ "New Caledonia", "NCL" },
		{ "New Zealand", "NZL" },
		{ "Nicaragua", "NIC" },
		{ "Nigeria", "NGA" },
		{ "Niger", "NER" },
		{ "North Africa", "NAF" },
		{ "North America", "NAC" },
		{ "Northern Mariana Islands", "MNP" },
		{ "Norway", "NOR" },
		{ "Oecd Members", "OED" },
		{ "Oman", "OMN" },
		{ "Other Small States", "OSS" },
		{ "Pacific Island Small States", "PSS" },
		{ "Pakistan", "PAK" },
		{ "Palau", "PLW" },
		{ "Panama", "PAN" },
		{ "Papua New Guinea", "PNG" },
		{ "Paraguay", "PRY" },
		{ "Peru", "PER" },
		{ "Philippines", "PHL" },
		{ "Poland", "POL" },
		{ "Portugal", "PRT" },
		{ "Puerto Rico", "PRI" },
		{ "Qatar", "QAT" },
		{ "Romania", "ROU" },
		{ "Russian Federation", "RUS" },
		{ "Rwanda", "RWA" },
		{ "Samoa", "WSM" },
		{ "San Marino", "SMR" },
		{ "Sao Tome And Principe", "STP" },
		{ "Saudi Arabia", "SAU" },
		{ "Senegal", "SEN" },
		{ "Serbia", "SRB" },
		{ "Seychelles", "SYC" },
		{ "Sierra Leone", "SLE" },
		{ "Singapore", "SGP" },
		{ "Sint Maarten (Dutch Part)", "SXM" },
		{ "Slovak Republic", "SVK" },
		{ "Slovenia", "SVN" },
		{ "Small States", "SST" },
		{ "Solomon Islands", "SLB" },
		{ "Somalia", "SOM" },
		{ "South Africa", "ZAF" },
		{ "South Asia (Ifc Classification)", "CSA" },
		{ "South Asia", "SAS" },
		{ "South Sudan", "SSD" },
		{ "Spain", "ESP" },
		{ "Sri Lanka", "LKA" },
		{ "St. Kitts And Nevis", "KNA" },
		{ "St. Lucia", "LCA" },
		{ "St. Martin (French Part)", "MAF" },
		{ "St. Vincent And The Grenadines", "VCT" },
		{ "Sub-Saharan Africa (All Income Levels)", "SSF" },
		{ "Sub-Saharan Africa (Developing Only)", "SSA" },
		{ "Sub-Saharan Africa (Ifc Classification)", "CAA" },
		{ "Sub-Saharan Africa Excluding South Africa And Nigeria", "XZN" },
		{ "Sub-Saharan Africa Excluding South Africa", "SXZ" },
		{ "Sudan", "SDN" },
		{ "Suriname", "SUR" },
		{ "Swaziland", "SWZ" },
		{ "Sweden", "SWE" },
		{ "Switzerland", "CHE" },
		{ "Syrian Arab Republic", "SYR" },
		{ "Tajikistan", "TJK" },
		{ "Tanzania", "TZA" },
		{ "Thailand", "THA" },
		{ "Timor-Leste", "TLS" },
		{ "Togo", "TGO" },
		{ "Tonga", "TON" },
		{ "Trinidad And Tobago", "TTO" },
		{ "Tunisia", "TUN" },
		{ "Turkey", "TUR" },
		{ "Turkmenistan", "TKM" },
		{ "Turks And Caicos Islands", "TCA" },
		{ "Tuvalu", "TUV" },
		{ "Uganda", "UGA" },
		{ "Ukraine", "UKR" },
		{ "United Arab Emirates", "ARE" },
		{ "United Kingdom", "GBR" },
		{ "United States", "USA" },
		{ "Upper Middle Income", "UMC" },
		{ "Uruguay", "URY" },
		{ "Uzbekistan", "UZB" },
		{ "Vanuatu", "VUT" },
		{ "Venezuela, Rb", "VEN" },
		{ "Vietnam", "VNM" },
		{ "Virgin Islands (U.S.)", "VIR" },
		{ "West Bank And Gaza", "PSE" },
		{ "World", "WLD" },
		{ "Yemen, Rep.", "YEM" },
		{ "Zambia", "ZMB" },
		{ "Zimbabwe", "ZWE" },
	};


	//public virtual ICollection<Product>
	//	Products
	//{ get; private set; } =
	//	new ObservableCollection<Product>();
}
